import { ImageSource, Sound, Resource, Loader } from 'excalibur'

const Resources = {
    Fish: new ImageSource('images/fish.png'),
    Background1: new ImageSource('images/background1.png'),
    Background2: new ImageSource('images/placeholder-map.png'),
    Bush1: new ImageSource('images/object-bush1.png'),
    Bush2: new ImageSource('images/object-bush2.png'),
    Bush3: new ImageSource('images/object-bush3.png'),
    Fence: new ImageSource('images/object-fence.png'),
    Bollard1: new ImageSource('images/object-bollard1.png'),
    Bollard2: new ImageSource('images/object-bollard2.png'),
    Bollard3: new ImageSource('images/object-bollard3.png'),
    Playground: new ImageSource('images/object-playground.png'),
    Hotel: new ImageSource('images/object-hotel.png'),
    Player: new ImageSource('images/player.png'),
    Player_frame1: new ImageSource('images/player_frame1.png'),
    Player_frame2: new ImageSource('images/player_frame2.png'),
    Player_loopSprite: new ImageSource('images/player_loopSprite.jpg'),
    Speedboost: new ImageSource('images/speedboost.png'),
    Lifeboost: new ImageSource('images/lifeboost.png'),
    atk_speed_frame1: new ImageSource('images/atk_speed_frame1.png'),
    atk_speed_frame2: new ImageSource('images/atk_speed_frame2.png'),
    atk_speed_frame3: new ImageSource('images/atk_speed_frame3.png'),
    Life: new ImageSource('images/life.png'),
    CockroachLeft1: new ImageSource('images/roach-left-1.png'),
    CockroachLeft2: new ImageSource('images/roach-left-2.png'),
    CockroachRight1: new ImageSource('images/roach-right-1.png'),
    CockroachRight2: new ImageSource('images/roach-right-2.png'),
    ReaperDefault: new ImageSource('images/reaper-right.png'),
    Lich1: new ImageSource('images/lich-right-1.png'),
    Lich2: new ImageSource('images/lich-right-2.png'),
    Lich3: new ImageSource('images/lich-right-3.png'),
    Lich4: new ImageSource('images/lich-right-4.png'),
    Lich5: new ImageSource('images/lich-right-5.png'),
    LichBlood1: new ImageSource('images/lich-blood-1.png'),
    LichProjectile: new ImageSource('images/lich-projectile.png'),
    Bow: new ImageSource('images/bow.png'),
    Spellbook: new ImageSource('images/spellbook.png'),
    Staff: new ImageSource('images/staff.png'),
    ThrowingAxe: new ImageSource('images/throwingAxe.png'),
    Arrow: new ImageSource('images/arrow.png'),
    StaffProjectile: new ImageSource('images/staffProjectile.png'),
    SpellbookProjectile: new ImageSource('images/magicTomeProjectile.png'),
    ReaperBlood1: new ImageSource('images/reaper-blood1.png'),
    ReaperBlood2: new ImageSource('images/reaper-blood2.png'),
    ReaperBlood3: new ImageSource('images/reaper-blood3.png'),
    Deathbanner: new ImageSource('images/deathbanner.png'),
    Dpad_equip: new ImageSource('images/Dpad.png'),

}
const ResourceLoader = new Loader([
    Resources.Player,
    Resources.Player_frame1,
    Resources.Player_frame2,
    Resources.Player_loopSprite,
    Resources.Background1,
    Resources.Background2,
    Resources.Bush1,
    Resources.Bush2,
    Resources.Bush3,
    Resources.Fence,
    Resources.Bollard1,
    Resources.Bollard2,
    Resources.Bollard3,
    Resources.Playground,
    Resources.Hotel,
    Resources.Speedboost,
    Resources.atk_speed_frame1,
    Resources.atk_speed_frame2,
    Resources.atk_speed_frame3,
    Resources.Lifeboost,
    Resources.Life,
    Resources.CockroachLeft1,
    Resources.CockroachLeft2,
    Resources.CockroachRight1,
    Resources.CockroachRight2,
    Resources.ReaperDefault,
    Resources.Lich1,
    Resources.Lich2,
    Resources.Lich3,
    Resources.Lich4,
    Resources.Lich5,
    Resources.LichProjectile,
    Resources.LichBlood1,
    Resources.Bow,
    Resources.Spellbook,
    Resources.Staff,
    Resources.ThrowingAxe,
    Resources.Arrow,
    Resources.StaffProjectile,
    Resources.SpellbookProjectile,
    Resources.ReaperBlood1,
    Resources.ReaperBlood2,
    Resources.ReaperBlood3,
    Resources.Deathbanner,
    Resources.Dpad_equip,
])

export { Resources, ResourceLoader }
